"""update mitigation report

Revision ID: 8301a6b398b7
Revises: d80591c4b0e0
Create Date: 2026-02-28 05:49:01.701498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8301a6b398b7'
down_revision: Union[str, Sequence[str], None] = 'd80591c4b0e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mitigation_reports', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('mitigation_reports', sa.Column('risk_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('mitigation_reports', sa.Column('generated_at', sa.DateTime(), nullable=True))
    op.alter_column('mitigation_reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_mitigation_reports_user_id'), table_name='mitigation_reports')
    op.create_unique_constraint(None, 'mitigation_reports', ['user_id'])
    op.drop_constraint(op.f('mitigation_reports_user_id_fkey'), 'mitigation_reports', type_='foreignkey')
    op.create_foreign_key(None, 'mitigation_reports', 'users', ['user_id'], ['id'])
    op.drop_column('mitigation_reports', 'created_at')
    op.alter_column('risk_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_risk_history_user_id'), table_name='risk_history')
    op.drop_constraint(op.f('risk_history_user_id_fkey'), 'risk_history', type_='foreignkey')
    op.create_foreign_key(None, 'risk_history', 'users', ['user_id'], ['id'])
    op.alter_column('risk_scores', 'risk_level',
               existing_type=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum'),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('stylometry_analysis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_stylometry_analysis_user_id'), table_name='stylometry_analysis')
    op.create_unique_constraint(None, 'stylometry_analysis', ['user_id'])
    op.drop_constraint(op.f('stylometry_analysis_user_id_fkey'), 'stylometry_analysis', type_='foreignkey')
    op.create_foreign_key(None, 'stylometry_analysis', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stylometry_analysis', type_='foreignkey')
    op.create_foreign_key(op.f('stylometry_analysis_user_id_fkey'), 'stylometry_analysis', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'stylometry_analysis', type_='unique')
    op.create_index(op.f('ix_stylometry_analysis_user_id'), 'stylometry_analysis', ['user_id'], unique=False)
    op.alter_column('stylometry_analysis', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('risk_scores', 'risk_level',
               existing_type=sa.String(),
               type_=postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level_enum'),
               existing_nullable=True)
    op.drop_constraint(None, 'risk_history', type_='foreignkey')
    op.create_foreign_key(op.f('risk_history_user_id_fkey'), 'risk_history', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_risk_history_user_id'), 'risk_history', ['user_id'], unique=False)
    op.alter_column('risk_history', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('mitigation_reports', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mitigation_reports', type_='foreignkey')
    op.create_foreign_key(op.f('mitigation_reports_user_id_fkey'), 'mitigation_reports', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'mitigation_reports', type_='unique')
    op.create_index(op.f('ix_mitigation_reports_user_id'), 'mitigation_reports', ['user_id'], unique=False)
    op.alter_column('mitigation_reports', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('mitigation_reports', 'generated_at')
    op.drop_column('mitigation_reports', 'risk_breakdown')
    op.drop_column('mitigation_reports', 'summary')
    # ### end Alembic commands ###
