"""Add profile_url and scan_type

Revision ID: fa7397748d9e
Revises: 8301a6b398b7
Create Date: 2026-02-28 07:41:18.733481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7397748d9e'
down_revision: Union[str, Sequence[str], None] = '8301a6b398b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('osint_data', sa.Column('profile_url', sa.String(), nullable=True))
    op.add_column('osint_data', sa.Column('scan_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('osint_data', 'scan_type')
    op.drop_column('osint_data', 'profile_url')
    # ### end Alembic commands ###
